### ISSUE TITLE
FR: Support Live Preview

### ISSUE THREAD

**Issue by robertandrews** [scottwillmoore/obsidian-short-internal-links-to-headings#1]
Can this work in Live Preview mode? I see it working in Reading mode.

**Comment by scottwillmoore** [comment]
Yep! It should work both in both editing (live preview) mode and when reading mode. I've updated the description to make it a bit clearer.

**Comment by scottwillmoore** [comment]
Just in case I misunderstood you, if it is not working in your live preview with the plugin installed (then this is a bug), let me know.
