### ISSUE TITLE
FR: Option for a symbol  to indicate whether you are linking to a header, a note or a block

### ISSUE THREAD

**Issue by ArtemisFowl-san** [scottwillmoore/obsidian-short-internal-links-to-headings#4]
Hey, thanks for making this plug in as it does get rid of a pain point I have had for a while.

I was wondering if you include the option for users to specify a symbol in the link which indicates whether something links to a header or a block. So maybe a link to a header could look like [[H: {{title of header}}]].

**Comment by scottwillmoore** [comment]
Hi, thanks for the feature request. I had kind of forgotten about links to blocks existed, as I don't use them.

This should be possible to implement. Just to clarify, do you want this symbol to appear just in editing mode when the ``[[...]]`` have appeared, or to appear at all times. There is some precedence in Obsidian for this, as a link symbol is appended to the end of external links, so perhaps it would be a good idea to match that format.

Also, at the moment, [links to blocks](https://help.obsidian.md/Linking+notes+and+files/Internal+links#Link+to+a+block+in+a+note) are shortened to `^37066d`, or `^quote-of-the-day`, as a side-effect of the way I process links to headings. Is this what is desired? Maybe, I should break this out into a separate issue for discussion.

**Comment by ArtemisFowl-san** [comment]
Hey, thanks for the quick reply. 

I think having the signal for headers appear at all times is preferable for me. 

And you are right, block ids are a bit of a different use case and probably warrant their own issue. I think the implementation you have for now is fine. Maybe giving users the option the option to separate the way they want block ids and headers to appear could be an option to make the plug in work better for different use cases, but I do not know how feasible this is.

**Comment by tim-hilde** [comment]
I find the way links to blocks are shown at the moment rather weird. I would love to see some different appearance for this use case

**Comment by scottwillmoore** [comment]
I'm away at the moment, but I have already implemented the majority of this feature. It just needs a little bit more work before I can release it. So, expect an update middle of March!

**Comment by scottwillmoore** [comment]
Check out the latest update, this should now be implemented 🚀.
